apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ .Values.basic.name }}-sc"
  namespace: "{{ .Values.basic.namespace }}"
stringData:
  SLACK_WEBHOOK_URL: "{{ .Values.secret.SLACK_WEBHOOK_URL }}"